### ISSUE TITLE
Small molecule conformer forcefield

### ISSUE THREAD

**Issue by what-is-what** [baker-laboratory/RoseTTAFold-All-Atom#103]
When running RF2AA with a protein and Fe-S cluster, I received the error "Failed to generate 3D coordinates of the molecule".
Presumably, this error occurs when generating conformers with OpenBarbell using the forcefield "mmff94".
Can I use another forcefield, such as GAFF, which is supported by OpenBabel?

**Comment by jayunruh** [comment]
Per issue #86 the "uff" forcefield seems to work--not sure about any accuracy differences.
