### ISSUE TITLE
small molecule conformer generation

### ISSUE THREAD

**Issue by what-is-what** [baker-laboratory/RoseTTAFold-All-Atom#111]
Is it necessary for small molecules to undergo conformer generation?

When utilizing the SDF structure of a small molecule, I believe that conformer generation may not be required.
Additionally, conformer generation can sometimes result in different structures, such as converting a ketone to an alcohol.

Furthermore, how can we use small molecule input as SMILES?
The code seems to support the SMILES representation of small molecules.

**Comment by Yang-Wang-2020** [comment]
Yes. smiles input works

**Comment by what-is-what** [comment]
I tried with smiles representation, but it also returns ketone to alcohol in several molecules.
How can we solve this problem?

**Comment by Yang-Wang-2020** [comment]
Same
