### ISSUE TITLE
Bug in merge_inputs.py

### ISSUE THREAD

**Issue by CYP152N1** [baker-laboratory/RoseTTAFold-All-Atom#12]
On the protein multimer prediction, I encounted the error shown below.

Traceback (most recent call last):
File "/Pass/to/RFAA/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 206, in main
runner.infer()
File "/Pass/to/RFAA/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 153, in infer
self.parse_inference_config()
File "/Pass/to/RFAA/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 93, in parse_inference_config
raw_data = merge_all(protein_inputs, na_inputs, sm_inputs, residues_to_atomize, deterministic=self.deterministic)
File "/Pass/to/RFAA/RoseTTAFold-All-Atom/rf2aa/data/merge_inputs.py", line 169, in merge_all
protein_inputs, protein_chain_lengths = merge_protein_inputs(protein_inputs, deterministic=deterministic)
File "/Pass/to/RFAA/RoseTTAFold-All-Atom/rf2aa/data/merge_inputs.py", line 76, in merge_protein_inputs
a3m_out["msa"],
TypeError: tuple indices must be integers or slices, not str

Is it correct way to marge msa?

-
a3m_out["msa"],
a3m_out["ins"],
+
a3m_out[0],
a3m_out[1],

**Comment by CYP152N1** [comment]
https://github.com/baker-laboratory/RoseTTAFold-All-Atom/pull/11

**Comment by r-krishna** [comment]
Hello, this is indeed a bug. `merge_a3m_homo` has a different return signature than the other functions. I will fix this imminently

**Comment by r-krishna** [comment]
could you share the case that you are trying to predict, so i can reproduce? just so i can make sure i have fixed your error properly

**Comment by gulseva** [comment]
Assuming that you are trying to predict a homo-multimer, adding an extra N- or C-terminal residue to break the symmetry is a temporary solution until the issue is fixed.

**Comment by r-krishna** [comment]
@CYP152N1 I think I have made the necessary bugfix but would appreciate it if you could send me a reproducible example so I can confirm before making the change in the repo
