### ISSUE TITLE
Is this an error?

### ISSUE THREAD

**Issue by remybonnav** [baker-laboratory/RoseTTAFold-All-Atom#131]
I am not sure what shoudl be the output of a run.

Here I get this for python -m rf2aa.run_inference --config-name protein_sm
with the example from the repository

/home/use/.conda/envs/RFAA/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'protein_sm': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Using the cif atom ordering for TRP.
./make_msa.sh examples/protein/7qxr.fasta 7qxr/A 4 64  pdb100_2021Mar03/pdb100_2021Mar03
Predicting: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.54sequences/s]
Running HHblits against UniRef30 with E-value cutoff 1e-10
- 16:27:22.840 INFO: Input file = 7qxr/A/hhblits/t000_.1e-10.a3m

- 16:27:22.840 INFO: Output file = 7qxr/A/hhblits/t000_.1e-10.id90cov75.a3m

- 16:27:22.965 WARNING: Maximum number 100000 of sequences exceeded in file 7qxr/A/hhblits/t000_.1e-10.a3m

- 16:29:52.494 INFO: Input file = 7qxr/A/hhblits/t000_.1e-10.a3m

- 16:29:52.494 INFO: Output file = 7qxr/A/hhblits/t000_.1e-10.id90cov50.a3m

- 16:29:52.617 WARNING: Maximum number 100000 of sequences exceeded in file 7qxr/A/hhblits/t000_.1e-10.a3m

Running PSIPRED
Running hhsearch
cat: 7qxr/A/t000_.ss2: No such file or directory

Then it finishes.

But I cannot find any pdb file output

**Comment by remybonnav** [comment]
Ok solved by
#106 
[https://github.com/baker-laboratory/RoseTTAFold-All-Atom/issues/106#issuecomment-2112950331](url)

**Comment by zehanna** [comment]
I encounter the same warning, but I do get a PDB file, which looks well when visualized in Chimera, and a *.pt file as output. The input_prep/make_ss.sh is already set to executable. Can I consider that everything went well then?
