### ISSUE TITLE
CUDA out of memory while running the 'nucleic_acid' example

### ISSUE THREAD

**Issue by wjk1214** [baker-laboratory/RoseTTAFold-All-Atom#22]
Thank you very much for providing us with such a useful tool. I have a question to ask: I successfully ran ‘Protein Monomers’ and 'protein_sm' using an RTX3060 with 12GB GPU memory. However, when I attempted to run ‘nucleic_acid’, I encountered a 'CUDA out of memory' error, despite the sequence not appearing particularly large. I'm unsure if this is normal? Thank you again for your contribution!

**Comment by masterwhook** [comment]
export this will be OK:
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb: 128

**Comment by wjk1214** [comment]
> export this will be OK: export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb: 128

Now it's working fine. Thank you very much for your generous response.

**Comment by wjk1214** [comment]
> export this will be OK: export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb: 128

Now it's working fine. Thank you very much for your generous response.
