### ISSUE TITLE
squashfs image was compressed with lz4, if it failed to run

### ISSUE THREAD

**Issue by blacktanktop** [baker-laboratory/RoseTTAFold-All-Atom#3]
Follow the instructions to install the RFAA and I ran it like this.
```
singularity run ./SE3nv-20240131.sif -m rf2aa.run_inference --config-name ./rf2aa/config/inference/protein_complex_sm.yaml
``` 
Then, I got the following error.

```
INFO:    squashfs image was compressed with lz4, if it failed to run, please contact image's author
INFO:    squashfs image was compressed with lz4, if it failed to run, please contact image's author
/usr/bin/python: Error while finding module specification for 'rf2aa.run_inference' (ModuleNotFoundError: No module named 'rf2aa')
```
How should I resolve this?
Also, I would like to know the proper command to run Singularity.

**Comment by Samuel-gwb** [comment]
I used apptainer to run the .sif, while meet similar error:

'''
INFO:    squashfs image was compressed with lz4, if it failed to run, please contact image's author
INFO:    squashfs image was compressed with lz4, if it failed to run, please contact image's author
FATAL:   container creation failed: mount hook function failure: mount /proc/self/fd/3->/home/gwb/install-dir/x86_64/var/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/3: squashfuse_ll exited with status 255: Squashfs image uses lz4 compression, this version supports only zlib.
'''

**Comment by Samuel-gwb** [comment]
> I used apptainer to run the .sif, while meet similar error:
> 
> ''' INFO: squashfs image was compressed with lz4, if it failed to run, please contact image's author INFO: squashfs image was compressed with lz4, if it failed to run, please contact image's author FATAL: container creation failed: mount hook function failure: mount /proc/self/fd/3->/home/gwb/install-dir/x86_64/var/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/3: squashfuse_ll exited with status 255: Squashfs image uses lz4 compression, this version supports only zlib. '''

"sudo apptainer ..." solved the problem

**Comment by blacktanktop** [comment]
I solved the Singlarity execution problem myself. This was a problem with our computing environment.
```
singularity run --nv -B /gs -B /apps -B /scr ./SE3nv-20240131.sif -m rf2aa.run_inference --config-name protein_complex_sm
```
 However, the following problem occurred, which is a separate Issue. #7

**Comment by patrickbryant1** [comment]
I also have this error. Please provide the version of appraiser you have used for building the image/installation of this.

**Comment by felixmb1** [comment]
I have a similar issue:
FATAL:   container creation failed: mount hook function failure: mount /proc/self/fd/3->/opt/apps/apptainer/1.1.8/var/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/3: kernel reported a bad superblock for squashfs image partition, possible causes are that your kernel doesn't support the compression algorithm or the image is corrupted

**Comment by merryxiang** [comment]
![error](https://github.com/baker-laboratory/RoseTTAFold-All-Atom/assets/31468565/d92030a1-c35d-45ab-b4ad-33f930189ee3)
anyone solved this problem？

**Comment by truatpasteurdotfr** [comment]
The provided container will not run on CentOS-7 as CONFIG_LZ4 is not defined in /boot/config-3.10.0-1160.* You can reconvert it provided you have a recent enough OS with apptainer/singularity installed:
```
[tru@maestro-submit recipes]$ cat SE3nv-20240131-convert/Singularity
BootStrap: localimage
From: /path/to/SE3nv-20240131.sif

%environment
export PATH=$PATH:/usr/local/cuda/bin

%runscript
exec python "$@"
```
run:
` apptainer build SE3nv-20240131-convert.sif SE3nv-20240131-convert/Singularity`

**Comment by r-krishna** [comment]
hello @amorehead has wrriten a PR (now merged in main) that moves to using mamba to install dependencies, let me know if you still encounter issues with the current README
