### ISSUE TITLE
Error in homodimer prediction

### ISSUE THREAD

**Issue by Garhorne0813** [baker-laboratory/RoseTTAFold-All-Atom#35]
I'm trying to predict a homodimer, which consists of two identical protein sequences. While inferring, I got this error:

`Traceback (most recent call last):
  File "/production/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 215, in main
    runner.infer()
  File "/production/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 161, in infer
    self.parse_inference_config()
  File "/production/RoseTTAFold-All-Atom/rf2aa/run_inference.py", line 96, in parse_inference_config
    raw_data = merge_all(protein_inputs, na_inputs, sm_inputs, residues_to_atomize, deterministic=self.deterministic)
  File "/production/RoseTTAFold-All-Atom/rf2aa/data/merge_inputs.py", line 171, in merge_all
    protein_inputs, protein_chain_lengths = merge_protein_inputs(protein_inputs, deterministic=deterministic)
  File "/production/RoseTTAFold-All-Atom/rf2aa/data/merge_inputs.py", line 78, in merge_protein_inputs
    a3m_out["msa"],
TypeError: tuple indices must be integers or slices, not str`

This error should be caused by the return value of the function merge_a3m_homo in data_loader_utils.py.

After `return msa, ins` is modified to `return {'msa': msa, 'ins': ins}`, the inference can work.

**Comment by Garhorne0813** [comment]
I input two identical protein sequences and I wanted to predict a homodimer, but I got two separated protein structures. Can you provide a solution?

`hash_list = [md5(input.sequence_string().encode()).hexdigest() for input in protein_inputs.values()]
lengths_list = [input.length() for input in protein_inputs.values()]
        
seen = set()
unique_indices = []
for idx, hash in enumerate(hash_list):
    if hash not in seen:
        unique_indices.append(idx)
        seen.add(hash)

unique_a3m = [a3m for i, a3m in enumerate(a3m_list) if i in unique_indices ]
unique_hashes = [value for index, value in enumerate(hash_list) if index in unique_indices]
unique_lengths_list = [value for index, value in enumerate(lengths_list) if index in unique_indices]`

Does this code in the merge_inputs.py function merge_protein_inputs prevent this from working?

**Comment by r-krishna** [comment]
yes, this is a bug. i have a branch that has this fixed in principle. I will try to get it merged tomorrow and follow up on this thread
