### ISSUE TITLE
Minor bug affecting expanding multi-MSAs

### ISSUE THREAD

**Issue by milafternoon** [baker-laboratory/RoseTTAFold-All-Atom#47]
Hi,

Thanks a lot for releasing the code! This is just to report a tiny bug that prevented the correct construction of an expanded MSA for a mixed protein homo/heterotrimer (a homodimer bound to a monomer).

If I'm not mistaken, line 48 in `data/merge_inputs.py` should read:
`a3m_out = join_msas_by_taxid(a3m_out, unique_a3m[i])`

**Comment by amorehead** [comment]
That does seem to be the case, at least from my perspective as well.

**Comment by jayunruh** [comment]
In a related issue it also appears that line 52 in `data/merge_inputs.py` should read `a3m_out['a3m'],a3m_out['ins'] = merge_a3m_homo(msa, ins, len(hash_list))` or alternatively merge_a3m_homo should be changed to output a dictionary.

**Comment by milafternoon** [comment]
Confirmed, I made the same change myself (first defining `a3m_out` as a copy of `a3m`), that was already pointed out here though: https://github.com/baker-laboratory/RoseTTAFold-All-Atom/issues/35
