### ISSUE TITLE
Are there any methods to relax the small molecule and protein complex?

### ISSUE THREAD

**Issue by simonkim1347** [baker-laboratory/RoseTTAFold-All-Atom#50]
I successfully installed and tested all eg files and ran my own files to get protein-small molecule complex.
Although I got the output protein structure in complex with small molecule, there are some steric hindrances and clashes..
Are there any methods to relax this structure?

**Comment by cyangNYU** [comment]
Maybe you can use Chimera (Amber minimization) or Schrodinger to relax the structures.

**Comment by HBioquant** [comment]
Maybe you can try the [relax script](https://github.com/HBioquant/DiffBindFR/blob/main/DiffBindFR/relax/pl.py#L461) based on the openff and openmm for the protein and ligand complex structures.
