### ISSUE TITLE
How can I specify Output files path?

### ISSUE THREAD

**Issue by Leo-T-Zang** [baker-laboratory/RoseTTAFold-All-Atom#65]
Hi @r-krishna ,

Wonder if I can specify the output files (.pdb and .pt) to specified path not just under current location.

Thanks.

**Comment by HBioquant** [comment]
See [here](https://github.com/baker-laboratory/RoseTTAFold-All-Atom/blob/main/rf2aa/run_inference.py#L141-L149).
