### ISSUE TITLE
pae_inter is NaN 

### ISSUE THREAD

**Issue by Leo-T-Zang** [baker-laboratory/RoseTTAFold-All-Atom#70]
Hi all,

I successfully ran a batch of DNA and protein docking with RFAA. However, I find out that for both my own files or example 7u7w, PAE_inter value is NaN in aux_pt files.

In this case, what metrice should I use or how do I compute this PAE_inter score?

Thanks a lot.

Update:
After quickly checked, in protein example 7u7w_protein_aux.pt, the pae_inter is also NaN. Other metrices are shown below:

```
{'plddts': tensor([[0.6665, 0.7220, 0.6728, 0.6760, 0.7203, 0.7498, 0.7685, 0.7472, 0.7559,
          0.8067, 0.8658, 0.8825, 0.9036, 0.8676, 0.8952, 0.8670, 0.8666, 0.8699,
          0.8487, 0.8824, 0.8733, 0.9043, 0.8770, 0.9122, 0.8870, 0.8748, 0.8501,
          0.8299, 0.8582, 0.8855, 0.8235, 0.8812, 0.8430, 0.8445, 0.8679, 0.9124,
          0.9028, 0.9223, 0.9068, 0.8896, 0.8301, 0.7905, 0.7782, 0.8047, 0.7904,
          ......
          0.7332, 0.8306, 0.8232, 0.8235, 0.8225, 0.8361, 0.8633, 0.8708, 0.8684,
          0.8616, 0.8816, 0.8324, 0.8878, 0.8761, 0.8881, 0.8338, 0.7956, 0.8117,
          0.8198, 0.8041, 0.6990]]),

 'pae': tensor([[[ 0.2541,  1.6876,  2.3954,  ..., 23.2573, 22.7284, 22.7535],
          [ 0.6448,  0.2505,  0.8906,  ..., 17.7422, 17.2152, 18.1647],
          [ 1.5417,  0.7148,  0.2508,  ..., 16.9036, 17.1059, 18.3577],
          ...,
          [14.3428, 14.1739, 13.7406,  ...,  0.2500,  0.4838,  1.0643],
          [15.5831, 15.8720, 15.7472,  ...,  0.3856,  0.2500,  0.7128],
          [17.8613, 18.5428, 18.1070,  ...,  1.9202,  0.7342,  0.2502]]]),

 'pde': tensor([[[0.1500, 0.2452, 0.4691,  ..., 3.3754, 3.2765, 3.1749],
          [0.2452, 0.1500, 0.2048,  ..., 3.1046, 3.5345, 3.5765],
          [0.4691, 0.2048, 0.1500,  ..., 3.0943, 2.9634, 3.5340],
          ...,
          [3.3754, 3.1046, 3.0943,  ..., 0.1500, 0.1627, 0.3063],
          [3.2765, 3.5345, 2.9634,  ..., 0.1627, 0.1500, 0.2166],
          [3.1749, 3.5765, 3.5340,  ..., 0.3063, 0.2166, 0.1500]]]),

 'mean_plddt': 0.8344975113868713,

 'mean_pae': 6.8152313232421875,

 'pae_prot': 6.8152313232421875,

 'pae_inter': nan,

 'same_chain': tensor([[[1, 1, 1,  ..., 1, 1, 1],
          [1, 1, 1,  ..., 1, 1, 1],
          [1, 1, 1,  ..., 1, 1, 1],
          ...,
          [1, 1, 1,  ..., 1, 1, 1],
          [1, 1, 1,  ..., 1, 1, 1],
          [1, 1, 1,  ..., 1, 1, 1]]])}
```

**Comment by luukhd2** [comment]
I have the same issue, were you able to resolve it?

**Comment by BigMary2001** [comment]
Excuse me, could you please help me with opening a file called '_aux.pt'? I tried to open it but it shows up as gibberish. Do you have any suggestions on how to open it or what program I might need?

**Comment by r-krishna** [comment]
`data = torch.load(file_aux, map_location="cpu")` will load the data into a python dictionary

**Comment by r-krishna** [comment]
PAE inter currently reproduces the pae_inter used in the paper which is for protein - atom interactions. you might want to do something like:
```
import matplotlib.pyplot as plt
plt.imshow(data["pae"])
```
to visualize the full pae matrix

**Comment by ning-2022** [comment]
> PAE inter currently reproduces the pae_inter used in the paper which is for protein - atom interactions. you might want to do something like:
> 
> ```
> import matplotlib.pyplot as plt
> plt.imshow(data["pae"])
> ```
> 
> to visualize the full pae matrix

Thanks for this suggestion.  But, I have a problem as following "
TypeError                                 Traceback (most recent call last)
Cell In[8], line 1
----> 1 plt.imshow(data["pae"])

File ~/mambaforge/envs/RFAA/lib/python3.10/site-packages/matplotlib/pyplot.py:3358, in imshow(X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, interpolation_stage, filternorm, filterrad, resample, url, data, **kwargs)
   3337 @_copy_docstring_and_deprecators(Axes.imshow)
   3338 def imshow(
   3339     X: ArrayLike | PIL.Image.Image,
   (...)
   3356     **kwargs,
   3357 ) -> AxesImage:
-> 3358     __ret = gca().imshow(
   3359         X,
   3360         cmap=cmap,
   3361         norm=norm,
   3362         aspect=aspect,
   3363         interpolation=interpolation,
   3364         alpha=alpha,
   3365         vmin=vmin,
   3366         vmax=vmax,
   3367         origin=origin,
   3368         extent=extent,
   3369         interpolation_stage=interpolation_stage,
   3370         filternorm=filternorm,
   3371         filterrad=filterrad,
   3372         resample=resample,
   3373         url=url,
   3374         **({"data": data} if data is not None else {}),
   3375         **kwargs,
   3376     )
   3377     sci(__ret)
   3378     return __ret

File ~/mambaforge/envs/RFAA/lib/python3.10/site-packages/matplotlib/__init__.py:1465, in _preprocess_data.<locals>.inner(ax, data, *args, **kwargs)
   1462 @functools.wraps(func)
   1463 def inner(ax, *args, data=None, **kwargs):
   1464     if data is None:
-> 1465         return func(ax, *map(sanitize_sequence, args), **kwargs)
   1467     bound = new_sig.bind(ax, *args, **kwargs)
   1468     auto_label = (bound.arguments.get(label_namer)
   1469                   or bound.kwargs.get(label_namer))

File ~/mambaforge/envs/RFAA/lib/python3.10/site-packages/matplotlib/axes/_axes.py:5759, in Axes.imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, interpolation_stage, filternorm, filterrad, resample, url, **kwargs)
   5756 if aspect is not None:
   5757     self.set_aspect(aspect)
-> 5759 im.set_data(X)
   5760 im.set_alpha(alpha)
   5761 if im.get_clip_path() is None:
   5762     # image does not already have clipping set, clip to axes patch

File ~/mambaforge/envs/RFAA/lib/python3.10/site-packages/matplotlib/image.py:723, in _ImageBase.set_data(self, A)
    721 if isinstance(A, PIL.Image.Image):
    722     A = pil_to_array(A)  # Needed e.g. to apply png palette.
--> 723 self._A = self._normalize_image_array(A)
    724 self._imcache = None
    725 self.stale = True

File ~/mambaforge/envs/RFAA/lib/python3.10/site-packages/matplotlib/image.py:693, in _ImageBase._normalize_image_array(A)
    691     A = A.squeeze(-1)  # If just (M, N, 1), assume scalar and apply colormap.
    692 if not (A.ndim == 2 or A.ndim == 3 and A.shape[-1] in [3, 4]):
--> 693     raise TypeError(f"Invalid shape {A.shape} for image data")
    694 if A.ndim == 3:
    695     # If the input data has values outside the valid range (after
    696     # normalisation), we issue a warning and then clip X to the bounds
    697     # - otherwise casting wraps extreme values, hiding outliers and
    698     # making reliable interpretation impossible.
    699     high = 255 if np.issubdtype(A.dtype, np.integer) else 1

TypeError: Invalid shape (1, 435, 435) for image data"    

That is complain from jupyter notebook.  I just used the command you provided.  
So pleas help me what's going on. 

BR,
Ning

**Comment by fglaser** [comment]
I also have issues plotting the values

e_prot': 4.171570301055908, 'pae_inter': 15.616806030273438, 'same_chain': tensor([[[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 1, 0, 0],
         [0, 0, 0,  ..., 0, 1, 0],
         [0, 0, 0,  ..., 0, 0, 1]]])}
>>> 
>>> import matplotlib.pyplot as plt
>>> plt.imshow(data["plddts"])
<matplotlib.image.AxesImage object at 0x7f0fcabbac50>
>>> 

Thanks
Fabian
