### ISSUE TITLE
rf2aa not found

### ISSUE THREAD

**Issue by velocirraptor23** [baker-laboratory/RoseTTAFold-All-Atom#91]
Hi,

I tried to run the next command line python -m rf2aa.run_inference --config-name protein.yaml, however there is no way to make it work. I have followed th step but seems rf2aa is not isntalled but did not get errors. te error I am getting is Error while finding module specification for 'rf2aa.run_inference' (ModuleNotFoundError: No module named 'rf2aa'). 

Any helo would be highly appreciated.

Cesar

**Comment by arupmondal835** [comment]
Did you export RoseTTAFold-All-Atom/ directory as a $PYTHONPATH?

**Comment by velocirraptor23** [comment]
Suddenly it started working. I think I puth the path as gusggested but also I reinstalled psipred from source.
